# Generated by Django 3.1.1 on 2020-09-15 12:39
import os
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_DB_NAME = os.environ.get('DB_NAME', "default")
        DJANGO_SU_NAME = os.environ.get('SU_NAME')
        DJANGO_SU_EMAIL = os.environ.get('SU_EMAIL')
        DJANGO_SU_PASSWORD = os.environ.get('SU_PASS')

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD)

        superuser.save()

    operations = [
        migrations.CreateModel(
            name='Django_ES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.IntegerField(max_length=5)),
                ('es_name', models.CharField(max_length=100)),
                ('es_url', models.CharField(max_length=450)),
                ('kibana_url', models.CharField(max_length=450)),
                ('desc', models.CharField(max_length=450)),
                ('es_health', models.CharField(max_length=10)),
                ('es_time', models.DateTimeField()),
            ],
        ),
        migrations.RunPython(generate_superuser),
    ]
