# Generated by Django 3.1.1 on 2020-09-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_es', '0002_auto_20200915_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='django_es',
            name='doc_color',
            field=models.CharField(default='red', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='django_es',
            name='es_json_docs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='django_es',
            name='es_query',
            field=models.CharField(default='blah', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='django_es',
            name='kibana_filter',
            field=models.CharField(default='blu', max_length=450),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='django_es',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='django_es',
            name='es_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='django_es',
            name='kibana_url',
            field=models.CharField(max_length=250),
        ),
    ]
