# Generated by Django 3.1.1 on 2020-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_es', '0003_auto_20200915_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django_es',
            name='kibana_url',
            field=models.CharField(max_length=450),
        ),
    ]
