# Generated by Django 3.1.1 on 2020-09-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_es', '0005_auto_20200917_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django_es',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='django_es',
            name='es_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='django_es',
            name='es_query',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='django_es',
            name='es_url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='django_es',
            name='kibana_filter',
            field=models.CharField(max_length=4500),
        ),
    ]
